package preflight

// SupportedArchs holds every arch_string declared by the installed
// exllamav3 architecture/*.py (reconciled at M2; draft/assistant models
// excluded — stone-llama v1 has no speculative-draft support).
//
// The list is allowed to lag reality: an architecture missing from here
// takes the warn path — never silent acceptance, never a refusal. An
// incomplete list degrades safely (G13).
var SupportedArchs = map[string]bool{
	"AfmoeForCausalLM":                      true,
	"ApertusForCausalLM":                    true,
	"ArceeForCausalLM":                      true,
	"Cohere2ForCausalLM":                    true,
	"CohereForCausalLM":                     true,
	"DeciLMForCausalLM":                     true,
	"DeepseekV3ForCausalLM":                 true,
	"DeepseekV4ForCausalLM":                 true,
	"Dots1ForCausalLM":                      true,
	"Ernie4_5_ForCausalLM":                  true,
	"Ernie4_5_MoeForCausalLM":               true,
	"Exaone4ForCausalLM":                    true,
	"Gemma2ForCausalLM":                     true,
	"Gemma3ForCausalLM":                     true,
	"Gemma3ForConditionalGeneration":        true,
	"Gemma4ForConditionalGeneration":        true,
	"Gemma4UnifiedForConditionalGeneration": true,
	"Glm4ForCausalLM":                       true,
	"Glm4MoeForCausalLM":                    true,
	"Glm4MoeLiteForCausalLM":                true,
	"Glm4vForConditionalGeneration":         true,
	"Glm4vMoeForConditionalGeneration":      true,
	"Glm5NextForConditionalGeneration":      true,
	"GlmMoeDsaForCausalLM":                  true,
	"GptOssForCausalLM":                     true,
	"HCXVisionV2ForCausalLM":                true,
	"HYV3ForCausalLM":                       true,
	"HyperCLOVAXForCausalLM":                true,
	"IQuestCoderForCausalLM":                true,
	"KimiLinearForCausalLM":                 true,
	"LagunaForCausalLM":                     true,
	"Lfm2ForCausalLM":                       true,
	"Lfm2MoeForCausalLM":                    true,
	"LlamaForCausalLM":                      true,
	"MiMoForCausalLM":                       true,
	"MiniMaxM2ForCausalLM":                  true,
	"Ministral3ForCausalLM":                 true,
	"Mistral3ForConditionalGeneration":      true,
	"MistralForCausalLM":                    true,
	"MixtralForCausalLM":                    true,
	"MuseGlimmerForConditionalGeneration":   true,
	"NemotronHForCausalLM":                  true,
	"Olmo3ForCausalLM":                      true,
	"OlmoHybridForCausalLM":                 true,
	"Phi3ForCausalLM":                       true,
	"Qwen2ForCausalLM":                      true,
	"Qwen2_5_VLForConditionalGeneration":    true,
	"Qwen3ForCausalLM":                      true,
	"Qwen3MoeForCausalLM":                   true,
	"Qwen3NextForCausalLM":                  true,
	"Qwen3VLForConditionalGeneration":       true,
	"Qwen3VLMoeForConditionalGeneration":    true,
	"Qwen3_5ForCausalLM":                    true,
	"Qwen3_5ForConditionalGeneration":       true,
	"Qwen3_5MoeForCausalLM":                 true,
	"Qwen3_5MoeForConditionalGeneration":    true,
	"Qwen4ExpForConditionalGeneration":      true,
	"SeedOssForCausalLM":                    true,
	"SmolLM3ForCausalLM":                    true,
	"SolarOpenForCausalLM":                  true,
	"Spark2_5ForCausalLM":                   true,
	"Step3p5ForCausalLM":                    true,
	"Step3p7ForConditionalGeneration":       true,
}
